# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fff-upload-challenge

    ports:
      - "53210:88"

    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
